package:
  name: pyocr
  version: "0.4.6"

source:
  fn: pyocr-0.4.6.tar.gz
  url: https://pypi.python.org/packages/6b/5e/0eaa5c939426b0f6a51f9fc883a1d756ad54ac9568faab129440a1dbca24/pyocr-0.4.6.tar.gz
  md5: 7814e58d36ed6a1d001c290135fafe5d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyocr = pyocr:main
    #
    # Would create an entry point called pyocr that calls pyocr.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pillow
    - six

  run:
    - python
    - pillow
    - six

test:
  # Python imports
  imports:
    - pyocr
    - pyocr.libtesseract

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jflesch/pyocr
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'A Python wrapper for OCR engines (Tesseract, Cuneiform, etc)'
  license_family: Public-Domain

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
